Repository isard-vdi/isard, pull requests merged in 2020-12, with the labels that each got.

#334 Feature/category dropdown
  api/src/api/libv2/api_users.py
  engine/engine/initdb/populate.py
  webapp/webapp/webapp/lib/admin_api.py
  webapp/webapp/webapp/static/admin/js/categories.js
  webapp/webapp/webapp/static/js/snippets/alloweds.js
  webapp/webapp/webapp/templates/admin/pages/categories_detail.html
  webapp/webapp/webapp/templates/admin/pages/users_modals.html
Labels: area/engine, area/webapp, kind/enhancement

#336 Fixed bug that did not allow domains edit
  webapp/webapp/webapp/lib/isardSocketio.py
  webapp/webapp/webapp/static/admin/js/domains.js
  webapp/webapp/webapp/static/js/desktops.js
Labels: area/webapp, kind/bug

#335 Feature/viewer jumper
  api/src/api/__init__.py
  api/src/api/libv2/api_desktops_nonpersistent.py
  api/src/api/libv2/api_desktops_persistent.py
  api/src/api/libv2/isardViewer.py
  api/src/api/static/logo.svg
  api/src/api/templates/error.html
  api/src/api/templates/jumper.html
  api/src/api/templates/logo.svg
  api/src/api/views/JumperViewerView.py
  api/src/api_client_test.py
  docker-compose-parts/api.devel.yml
  docker-compose-parts/webapp.devel.yml
  docker/portal/haproxy.conf
  webapp/webapp/webapp/admin/views/AdminDomainsViews.py
  webapp/webapp/webapp/lib/admin_api.py
  webapp/webapp/webapp/lib/api.py
  webapp/webapp/webapp/static/admin/js/domains.js
  webapp/webapp/webapp/static/js/desktops.js
  webapp/webapp/webapp/templates/admin/pages/domains_modals.html
  webapp/webapp/webapp/templates/pages/desktops_detail.html
  webapp/webapp/webapp/templates/pages/desktops_modals.html
  webapp/webapp/webapp/views/DesktopViews.py
Labels: area/webapp, kind/enhancement, stage/4-finished

#341 relaxed time between virtlogd and libvirt that avoids race bug sometimes
  docker/hypervisor/run.sh
Labels: kind/bug

#343 fixes for tcp mode to reduce spice delay and usb passthrough
  docker/portal/haproxy.conf
Labels: kind/enhancement

#340 working audio
  docker/hypervisor/Dockerfile
  docker/hypervisor/qemu-kvm
Labels: area/docker, kind/bug, stage/3-to-review

#347 Allows access to direct viewer link when desktop started. Also fixed …
  webapp/webapp/webapp/static/admin/js/domains.js
  webapp/webapp/webapp/static/js/desktops.js
Labels: kind/enhancement

#342 Force hypervisor
  api/src/api/libv2/webapp_quotas.py
  docker-compose-parts/engine.devel.yml
  engine/engine/engine/controllers/ui_actions.py
  engine/engine/engine/services/db/domains.py
  engine/engine/engine/services/evaluators/ux_eval.py
  webapp/webapp/webapp/lib/admin_api.py
  webapp/webapp/webapp/lib/api.py
  webapp/webapp/webapp/lib/isardSocketio.py
  webapp/webapp/webapp/lib/quotas.py
  webapp/webapp/webapp/static/admin/js/domains.js
  webapp/webapp/webapp/static/js/desktops.js
  webapp/webapp/webapp/static/js/snippets/domain_hardware.js
  webapp/webapp/webapp/static/js/snippets/domain_hotplugged.js
  webapp/webapp/webapp/templates/admin/pages/domains_modals.html
  webapp/webapp/webapp/templates/admin/pages/templates_detail.html
  webapp/webapp/webapp/templates/pages/desktops_detail.html
Labels: area/webapp, kind/enhancement, stage/3-to-review

#348 Fixes bug when restarting hypervisor
  docker/hypervisor/run.sh
Labels: kind/bug

#350 fixed shared range
  docker/hypervisor/networks/shared.xml
Labels: kind/bug

#351 Fix hypervisor shared network dhcp range
  docker/hypervisor/networks/shared.xml
Labels: kind/bug, stage/3-to-review

#352 Fix hypervisor spice certs owner when upgrading
  CHANGELOG.md
Labels: kind/bug, stage/3-to-review
